In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Activation
import keras
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
df = pd.read_csv("Churn_Modelling.csv")
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [ ]:
df = df.fillna(df.mean())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


<ipython-input-117-c34e1aa43e71>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df = df.fillna(df.mean())


In [ ]:
X = df.iloc[:, 3:-1]
y = df.iloc[:, -1]
y.unique()

array([1, 0])

In [ ]:
X = pd.get_dummies(X, columns=["Geography", "Gender"], drop_first=True)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
X_train_scaled.shape

(5170, 10)

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=64, activation='relu', input_dim=X_train_scaled.shape[1]),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(units=32, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(units=1, activation='sigmoid')
])


In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
history = model.fit(X_train_scaled, y_train, batch_size=64, epochs=10, validation_split=0.2)

Epoch 1/10
100/100 [==============================] - 4s 6ms/step - loss: 0.5162 - accuracy: 0.7761 - val_loss: 0.4355 - val_accuracy: 0.8156
Epoch 2/10
100/100 [==============================] - 0s 3ms/step - loss: 0.4459 - accuracy: 0.8016 - val_loss: 0.4124 - val_accuracy: 0.8263
Epoch 3/10
100/100 [==============================] - 0s 3ms/step - loss: 0.4284 - accuracy: 0.8150 - val_loss: 0.3990 - val_accuracy: 0.8325
Epoch 4/10
100/100 [==============================] - 0s 3ms/step - loss: 0.4137 - accuracy: 0.8261 - val_loss: 0.3865 - val_accuracy: 0.8425
Epoch 5/10
100/100 [==============================] - 0s 4ms/step - loss: 0.3981 - accuracy: 0.8334 - val_loss: 0.3748 - val_accuracy: 0.8487
Epoch 6/10
100/100 [==============================] - 0s 5ms/step - loss: 0.3882 - accuracy: 0.8417 - val_loss: 0.3661 - val_accuracy: 0.8500
Epoch 7/10
100/100 [==============================] - 1s 6ms/step - loss: 0.3742 - accuracy: 0.8459 - val_loss: 0.3623 - val_accuracy: 0.8531
Epoch 

In [ ]:
loss, accuracy = model.evaluate(X_test_scaled, y_test)
print(f"Test loss: {loss:.4f}, Test accuracy: {accuracy:.4f}")

63/63 [==============================] - 0s 2ms/step - loss: 0.3439 - accuracy: 0.8590
Test loss: 0.3439, Test accuracy: 0.8590


In [ ]:
y_pred = (model.predict(X_test_scaled) > 0.5).astype("int32")
y_pred

63/63 [==============================] - 0s 2ms/step


array([[0],
       [0],
       [0],
       ...,
       [1],
       [0],
       [0]], dtype=int32)

Applying SVM

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [ ]:
data = pd.read_csv("winequalityN.csv")
data

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     white            7.0             0.270         0.36            20.7   
1     white            6.3             0.300         0.34             1.6   
2     white            8.1             0.280         0.40             6.9   
3     white            7.2             0.230         0.32             8.5   
4     white            7.2             0.230         0.32             8.5   
...     ...            ...               ...          ...             ...   
6492    red            6.2             0.600         0.08             2.0   
6493    red            5.9             0.550         0.10             2.2   
6494    red            6.3             0.510         0.13             2.3   
6495    red            5.9             0.645         0.12             2.0   
6496    red            6.0             0.310         0.47             3.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0         0.045                 45.0                 170.0  1.00100  3.00   
1         0.049                 14.0                 132.0  0.99400  3.30   
2         0.050                 30.0                  97.0  0.99510  3.26   
3         0.058                 47.0                 186.0  0.99560  3.19   
4         0.058                 47.0                 186.0  0.99560  3.19   
...         ...                  ...                   ...      ...   ...   
6492      0.090                 32.0                  44.0  0.99490  3.45   
6493      0.062                 39.0                  51.0  0.99512  3.52   
6494      0.076                 29.0                  40.0  0.99574  3.42   
6495      0.075                 32.0                  44.0  0.99547  3.57   
6496      0.067                 18.0                  42.0  0.99549  3.39   

      sulphates  alcohol  quality  
0          0.45      8.8        6  
1          0.49      9.5        6  
2          0.44     10.1        6  
3          0.40      9.9        6  
4          0.40      9.9        6  
...         ...      ...      ...  
6492       0.58     10.5        5  
6493        NaN     11.2        6  
6494       0.75     11.0        6  
6495       0.71     10.2        5  
6496       0.66     11.0        6  

[6497 rows x 13 columns]

In [ ]:
data = data.dropna()
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6463 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   type                  6463 non-null   object 
 1   fixed acidity         6463 non-null   float64
 2   volatile acidity      6463 non-null   float64
 3   citric acid           6463 non-null   float64
 4   residual sugar        6463 non-null   float64
 5   chlorides             6463 non-null   float64
 6   free sulfur dioxide   6463 non-null   float64
 7   total sulfur dioxide  6463 non-null   float64
 8   density               6463 non-null   float64
 9   pH                    6463 non-null   float64
 10  sulphates             6463 non-null   float64
 11  alcohol               6463 non-null   float64
 12  quality               6463 non-null   int64  
dtypes: float64(11), int64(1), object(1)
memory usage: 706.9+ KB


In [ ]:
def check_condition(value):
    if value<=5:
      return 4
    else:
      return 8

data['quality_'] = data['quality'].apply(check_condition)
data.drop(columns=['quality'], inplace=True)
y2 = data.iloc[:,-1]
y2.unique()

<ipython-input-89-d720a8934ae3>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['quality_'] = data['quality'].apply(check_condition)
<ipython-input-89-d720a8934ae3>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(columns=['quality'], inplace=True)


array([8, 4])

In [ ]:
X = data.iloc[:, 3:-1]
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6463 entries, 0 to 6496
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   citric acid           6463 non-null   float64
 1   residual sugar        6463 non-null   float64
 2   chlorides             6463 non-null   float64
 3   free sulfur dioxide   6463 non-null   float64
 4   total sulfur dioxide  6463 non-null   float64
 5   density               6463 non-null   float64
 6   pH                    6463 non-null   float64
 7   sulphates             6463 non-null   float64
 8   alcohol               6463 non-null   float64
dtypes: float64(9)
memory usage: 504.9 KB


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y2, test_size=0.2, random_state=42)

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
svm_model = SVC(kernel='linear', C=1.0)

In [ ]:
svm_model.fit(X_train_scaled, y_train)

SVC(C=100.0, kernel='linear')

In [ ]:
y_pred = svm_model.predict(X_test_scaled)
y_pred

array([8, 8, 8, ..., 8, 4, 4])

In [ ]:
confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)

Confusion Matrix:
[[236 246]
 [130 681]]


In [ ]:
accuracy = accuracy_score(y_test,y_pred)*100
accuracy

70.92034029389018

Applying PCA

In [ ]:
pca = PCA(n_components=9)
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

In [ ]:
svm_model = SVC(kernel='linear', C=1.0)

In [ ]:
svm_model.fit(X_train_pca, y_train)

SVC(kernel='linear')

In [ ]:
y1_pred = svm_model.predict(X_test_pca)

In [ ]:
accuracy = accuracy_score(y_test,y1_pred)*100
accuracy

70.92034029389018